service: scam-v2
frameworkVersion: '2'

plugins:
  - serverless-import-apigateway
  - serverless-plugin-log-subscription
  - serverless-offline

custom:
  # 기존 rest api-gateway 연결용 게이트웨이 명칭
  importApiGateway:
    name: ${self:service}-gateway-${sls:stage}
  # DynamoDB 설정
  database: ${file(serverless-config/${sls:stage}/database.yml)}

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-northeast-2
  stackName: ${self:service}-${sls:stage}
  logRetentionInDays: 90
  environment:
    NODE_PATH: './:/opt'
    PROFILE: ${sls:stage}
    SERVICE: ${self.service}
    TZ: 'Asia/Seoul'
    TABLE_NAME: ${self:custom.database.scamInquire.table}
    HASH_KEY: ${self:custom.database.hmacSha256Key}

package:
  patterns:
    - '!serverless-config/**'
    - '!node_modules/**'
    - '!package.json'
    - '!yarn-lock.json'
    - '!*.sh'
    - '!readme.md'
    - '!test/**'

layers:
  CommonLayer:
    path: node_modules
    name: ${self:service}-common-layer-${sls:stage}
    description: ${self:service} common lambda nodejs layer
    allowedAccounts:
      - '*'
    compatibleRuntimes:
      - nodejs14.x

functions:
  search:
    handler: functions/handler.main
    description: ${self:service} function
    package:
      patterns:
        - functions/handler
        - functions/search/**
        - common/**
    layers:
      - { Ref: CommonLayerLambdaLayer }
    events:
      - http:
          path: /search
          method: post
          private: true
